#!/usr/bin/env bash
# Install nginx on your web-01
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx start
