#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server

sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  soufiane-oumalek_frontend
        bind *:80
        mode http
        default_backend soufiane-oumalek_backend
backend   soufiane-oumalek_backend
        balance roundrobin
        server 394828-web-01 54.90.21.102:80 check
        server 394828-web-02 54.237.42.194:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
