#!/usr/bin/env bash
#configures a server to the above requirements
rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart server
sudo service nginx restart
