#!/usr/bin/env bash
#displays numbers from 1 to 100
#for i in {1..100}
i=1
while [ "$i" -le 100 ]
do
    if !(( i % 3 )) && !(( i % 5 ))
    then
        echo "FizzBuzz"
    if (( i % 3 ))
    then
        echo "Fizz"
    if ((i % 5 ))
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    ((i++))
done