#!/usr/bin/env bash
#displays the content of the file /etc/passwd
#username
#user id
#Home directory path for the user
file="/etc/passwd"
while IFS= read -r file
do
    echo "$file" | cut -d ':' -f1,3,6
done <"$file"
