#!/usr/bin/env bash
#displays Best School 10 times with Hi in line 10
c=0
while [ $c -lt 10 ]
do
    if [ $c -eq 10 ]
    then
        echo "Hi"
    fi
        echo "Best School"
        ((c++))
done
