#!/usr/bin/env bash
#that loops from 1 to 10 and:
#displays bad luck  4th loop
#displays good luck 8th loop
c=0
while [ $c -lt 10 ]
do
    if [ $c -eq 3 ]
    then
        echo "bad luck"
    elif [ $c -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
        ((c++))
done
