#!/usr/bin/env bash
#configures an Ubuntu server with the below
cp /etc/hosts ~/hosts.new
sed -i '$ a\127.0.0.1 localhos' ~/hosts.new
sed -i '$ a\8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
